### ISSUE TITLE
what is "clsf-mask-one" and "laye-mask-one" for ?

### ISSUE THREAD

**Issue by yuang-lee** [JinheonBaek/FED-PUB#1]
As title, I am not sure about what these two config are doing, if anyone can give me some simple explaination ?

Aprreciate it !

**Comment by JinheonBaek** [comment]
Thanks for your interest and for asking a good question.
* laye-mask-one: this is the mask of the GNN layer
* clsf-mask-one: this is the mask of the last classification (linear) layer

In our proposed method, during weight aggregation for FL, we filter out irrelevant information from subgraphs of different communities, which is operationalized with these local masks (i.e., masking out weights that are not relevant to local tasks but aggregated from heterogeneous subgraphs, which results in preserving only useful weights).

**Comment by yuang-lee** [comment]
Thank you for the reply, Great work !
